# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Upload Binary to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "eu-central-1"
      run: |
        aws s3 cp ./simplemath s3://${{ secrets.TARGET_BUCKET }}/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: S3 Download Artifact
      uses: blakjak44/s3-download-artifact@v0.0.5
      with:
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        aws_secret_access_key: ${{ secrets.SECRET_KEY }}
        aws_region: "eu-central-1"
        bucket: ${{ secrets.TARGET_BUCKET }}
        name: "simplemath"
        path: "./"

    - name: Check files
      run: |
        ls ./
        pwd ./

    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: 3.122.194.120
        user: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        scp: /artifacts/simplemath => /home/ec2-user/app/simplemath
        last_ssh: chmod +x /home/ec2-user/app/simplemath && /home/ec2-user/app/simplemath/simplemath
          
