# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Upload Binary to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "eu-central-1"
      run: |
        aws s3 cp ./simplemath s3://${{ secrets.TARGET_BUCKET }}/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download S3
      # You may pin to the exact commit or the version.
      # uses: joutvhu/download-s3@07d7cec53b55fdc9145b4d65afdf7ec98939e88f
      uses: joutvhu/download-s3@v1.0.0
      with:
        # AWS access key ID.
        aws_access_key_id: ${{ secrets.ACCESS_KEY }}
        # AWS secret access key.
        aws_secret_access_key: ${{ secrets.SECRET_KEY }}
        # The region to send service requests to.
        aws_region: "eu-central-1"
        # The bucket name containing the files to download.
        aws_bucket: ${{ secrets.TARGET_BUCKET }}
        # The directory (or file path) on the bucket to which you want to download.
        # source: # optional, default is 
        # The local directory (or file path) where files are saved.
        target: .
          

    
    # - name: S3 Download Artifact
    #   uses: blakjak44/s3-download-artifact@v0.0.5
    #   with:
    #     aws_access_key_id: ${{ secrets.ACCESS_KEY }}
    #     aws_secret_access_key: ${{ secrets.SECRET_KEY }}
    #     aws_region: "eu-central-1"
    #     bucket: ${{ secrets.TARGET_BUCKET }}
    #     name: "simplemath"
    #     path: ./

    - name: Check files
      run: ls ./

    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: 3.70.96.177
        user: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
        scp: /artifacts/simplemath => /home/ec2-user/app/simplemath
        last_ssh: chmod +x /home/ec2-user/app/simplemath && /home/ec2-user/app/simplemath/simplemath
          
